{{- if (.Values.serviceAccount).enabled  | default false -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Values.namespace }}
  labels:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}